#!/bin/awk -f 

# Awk program to read CSV data and parse out relevant real estate records
# This particular program parses for single-family dwellings, saving the
# relevant data in HTML, preserving only date, subdivision name, lot,
# block, and value.

function parse() {

	#$6 ~ /^single family dwelling$/ {printf("\t<td>%s</td>\n", $i)} >> "parseData.html"

}

BEGIN {
	# Build the start of the HTML file
	print "<html>\n\n" > "parseData.html"
	print "<head>\n" >> "parseData.html"
	print "<title>Single Family Dwelling</title>\n" >> "parseData.html"
	print "</head>\n\n" >> "parseData.html"
	print "<body>\n" >> "parseData.html"
	print "<h1>Records</h1>\n\n" >> "parseData.html"
	print "<table cellspacing="100">\n" >> "parseData.html"
	print "<tr>\n" >> "parseData.html"
	print "\t<td>DATE</td>\n" >> "parseData.html"
	print "\t<td>SUBDIVISION</td>\n" >> "parseData.html"
	print "\t<td>LOT</td>\n" >> "parseData.html"
	print "\t<td>BLOCK</td>\n" >> "parseData.html"
	print "\t<td>VALUE</td>\n" >> "parseData.html"
	print "</tr>\n" >> "parseData.html"
#	print "<tr>" >> "parseData.html"

	# define divisions between cells
	FPAT = "([^,]+)|(\"[^\"]+\")"
}

{

# 1-date, 5-subdivision, 6-lot, 7-block, 8-value, print based on 3
	

	if(tolower($3) ~ /^single family dwelling$/) {
		print "<tr>" >> "parseData.html"
		for(i=1; i<= NF; i++) {
			if(i==1) {
				printf("\t<td>%s</td>\n", $i) >> "parseData.html"
			}
			if(i==5) {
				printf("\t<td>%s</td>\n", $i) >> "parseData.html"
			}
			if(i==6) {
				printf("\t<td>%s</td>\n", $i) >> "parseData.html"
			}
			if(i==7) {
				printf("\t<td>%s</td>\n", $i) >> "parseData.html"
			}
			if(i==8) {
				printf("\t<td>%s</td>\n", $i) >> "parseData.html"
			}
		}	
		print "</tr>\n" >> "parseData.html"
	}
	

#	for (i=1; i<= NF; i++) {
#		if($i == 1) {
#			printf() >> "parseData.html"
#		}
#		printf("\t<td>%s\t", $i) >> "parseData.html"
#	} 
#	print "</td>\n\n" >> "parseData.html"

}
END {
#	print "</tr>\n" >> "parseData.html"
	print "</table>\n\n" >> "parseData.html"
	print "</body>\n" >> "parseData.html"
	print "</html>\n" >> "parseData.html"
}
